Artemvwv/password generator
Martyniuk/learning-in-pair pull request #37
Opened 2022-09-13 18:18 UTC by ArtemVMV

Please add new project

2022-09-13 18:48 UTC, Martyniuk approved these changes

2022-09-13 18:50 UTC, Martyniuk requested changes

2022-09-13 18:50 UTC, Martyniuk commented on index.html
> +                  <a href="artemVMV/Password Generator/index.html">Profile-card</a>Personal cards
Please check href path

2022-09-14 18:31 UTC, ArtemVMV commented on index.html
> +                  <a href="artemVMV/Password Generator/index.html">Profile-card</a>Personal cards
done

2022-09-15 17:20 UTC, Martyniuk approved these changes

2022-09-15 18:07 UTC, merged