Calculator
Martyniuk/learning-in-pair pull request #9
Opened 2021-04-29 20:54 UTC by LenoGe

2021-04-30 19:19 UTC, Martyniuk requested changes
Я не могу оставить комменты на файлах, потому перечислю ниже:

1. /img/image credit.rtf - название файла без пробела должно быть
2. файл html внутри `artem/FrontMastersForm/FEmasters_bootcamp_artem.html` должен называться "index"

а еще ты походу не поставил себе commitlint - потому что commit message не по конвенции 

перед след комитом - выполни комманду yarn

2021-05-03 06:31 UTC, Martyniuk reviewed
Ты yarn команду выполнил перед коммитом?

2021-05-03 06:32 UTC, LenoGe commented
Да, выполнял и перед и до

On Mon, May 3, 2021, 09:31 Volodymyr Martyniuk ***@***.***>
wrote:

> *@Martyniuk* commented on this pull request.
>
> Ты yarn команду выполнил перед коммитом?
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/Martyniuk/learning-in-pair/pull/9#pullrequestreview-650109063>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AKC2A3KKXBWSTRYGKTKUJV3TLY7NHANCNFSM432WBQSQ>
> .
>

2021-05-03 06:43 UTC, Martyniuk approved these changes

2021-05-04 11:11 UTC, merged